# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Custom vars
version:          2.1.0

github:           metadata

repository:       username/username.github.io
userdisqus:       username

# Setup
author:
  name:           "Alberto Castelo"
  url:            https://twitter.com/acaste10
  twitter:        acaste10

paginate:         5

title:            "Alberto Castelo"
tagline:          "Artificial Intelligence Engineer"
description:      "Separating the Signal from the Noise"
locale:           es_es
encoding:         utf-8
url:              https://AlbertoCastelo.github.io
baseurl:          https://AlbertoCastelo.github.io/  
google_analytics: UA-XXXXXXXXX-X